line-length = 143

lint.select = ["ALL"]

lint.ignore = [
  "ANN",  # type annotation
  "D100",  # Missing docstring in public module
  "D101",  # Missing docstring in public class
  "D102",  # Missing docstring in public method
  "D103",  # Missing docstring in public function
  "D104",  # Missing docstring in public package
  "D105",  # Missing docstring in magic method
  "D107",  # Missing docstring in `__init__`
  "D203",  # 1 blank line required before class docstring
  "D205",  # 1 blank line required between summary line and description
  "D213",  # incompatible. Ignoring `multi-line-summary-second-line`
  "D401",  # First line of docstring should be in imperative mood
  "D417",  # Missing argument descriptions in the docstring
  "FIX002",  # Line contains TODO, consider resolving the issue
  "TD002",  # Missing author in TODO
  "TD003",  # Missing issue link on the line following this TODO
  "TRY003",  # Avoid specifying long messages outside the exception class
]

[lint.extend-per-file-ignores]
"docs/*" = [
  "A001",  # builtin-variable-shadowing
  "ARG001",
  "C408",
  "D100",  # Missing docstring in public module
  "D400",
  "D415",
  "E402",  # Module level import not at top of file
  "E501",  # Line too long
  "ERA001",  # Found commented-out code
  "ERA001",  # Found commented-out code
  "EXE001",  # Shebang is present but file is not executable
  "EXE003",
  "EXE005",
  "F811",
  "PD011",
  "PD901",
  "PLR2004",
  "PTH103",
  "PTH107",
  "PTH110",
  "PTH118",
  "RUF015",
  "T201",
]
"test_*.py" = [
  "ANN001",  # Missing type annotation for function argument
  "ANN101",  # Missing type annotation for `self` in method
  "ANN201",  # Missing return type annotation for public function
  "ANN202",  # Missing return type annotation for private function
  "D100",  # Missing docstring in public module
  "D101",  # Missing docstring in public class
  "D102",  # Missing docstring in public method
  "D104",  # Missing docstring in public package
  "E501",  # Line too long (113 > 79)
  "ERA001",  # Found commented-out code
  "INP001",  # File is part of an implicit namespace package
  "PD901",  # Avoid using the generic variable name `df` for DataFrames
  "PLR0913",  # Too many arguments in function definition
  "PLR2004",  # Magic value used in comparison
  "S101",  # Use of assert detected
  "SLF001",  # Private member accessed
]
# nbqa-ruff acts on converted .py so we cannot glob .ipynb :-/
# https://github.com/nbQA-dev/nbQA/issues/823
"notebooks/*" = [
  "ANN001",  # Missing type annotation for function argument
  "ANN201",  # Missing return type annotation for public function
  "B018",  # Found useless expression. Either assign it to a variable or remove it
  "D100",  # Missing docstring in public module
  "D103",  # Missing docstring in public function
  "E402",  # Module level import not at top of file
  "FBT003",  # Boolean positional value in function call
  "INP001",  # File is part of an implicit namespace package
  "PD901",  # Avoid using the generic variable name `df` for DataFrames
  "T201",  # `print` found"
]
[lint.pycodestyle]
max-doc-length = 180
